language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn build
after_success:
  - yarn build-storybook

deploy:
  - provider: script
    script: yarn semantic-release
    skip-cleanup: true
    on:
      branch: master
  - provider: pages
    local-dir: "./storybook-static"
    skip-cleanup: true
    github-token: $GH_TOKEN
    keep-history: true
    on:
      branch: master